# Generated by Django 6.0.5 on 2026-05-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('airtel_money', 'Airtel Money'), ('mpamba', 'Mpamba'), ('bank', 'Bank Transfer')], max_length=50)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('proof_image', models.ImageField(upload_to='payments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('songs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
        ),
    ]
