# Generated by Django 6.0.5 on 2026-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
